src/delta_x/module/dashboard/urls.py
from django.urls import path, re_path

from .authentication.views import (
    LoginViewSet,
    LogoutViewSet,
    ResetPasswordViewSet,
    PasswordResetConfirmViewSet,
    PasswordResetCompleteViewSet,
    SignUpViewSet)
from .profile.views import ProfileViews
from .views import IndexDashboardViews

app_name = 'dashboard'
urlpatterns = [
    path("", IndexDashboardViews.as_view(), name="index"),
    path('login/', LoginViewSet.as_view(), name="login"),
    path('logout/', LogoutViewSet.as_view(), name="logout"),
    path('register/', SignUpViewSet.as_view(), name="register"),
    path('password_reset/', ResetPasswordViewSet.as_view(), name="password_reset"),
    path('password_reset_done/', PasswordResetCompleteViewSet.as_view(), name="password_reset_done"),
    path('password-reset-confirm/<uidb64>/<token>/',
         PasswordResetConfirmViewSet.as_view(),
         name='password_reset_confirm'),

    re_path(r'^profile/(?P<pk>\d+)/edit$', ProfileViews.as_view(), name="profile"),
]

src/delta_x/module/urls.py
app_name = 'module'
urlpatterns = [

]

src/delta_x/urls.py
from django.urls import include, path, re_path
from django.conf.urls import (
    handler400,
    handler403,
    handler404,
    handler500)

from .api.utiles import schema_view
from .api.routers import router

handler403 = 'module.cores.custom_permission_denied_view'
handler404 = 'module.cores.custom_page_not_found_view'
handler500 = 'module.cores.custom_error_view'

urlpatterns = [
    path('api-auth/', include('rest_framework.urls')),
    path('api/', include(router.urls)),
    path('module/', include('delta_x.module.urls', namespace='module')),
    path('dashboard/', include('delta_x.module.dashboard.urls', namespace='dashboard')),
    re_path(r'^docs(?P<format>\.json|\.yaml)$', schema_view.without_ui(
        cache_timeout=0), name='schema-json'),
    path('docs/', schema_view.with_ui('swagger',
         cache_timeout=0), name='schema-swagger-ui'),
]

src/delta_x/module/cores/models.py
from django.db import models


class Info(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    deleted_at = models.DateTimeField(null=True, blank=True)
    is_deleted = models.BooleanField(default=False)

    class Meta:
        abstract = True

src/delta_x/module/users/forms.py
from django.forms import ModelForm
from .models import Customer, User


class CustomerCreationForm(ModelForm):

    class Meta:
        model = Customer
        fields = ('user',)


class CustomerChangeForm(ModelForm):

    class Meta:
        model = Customer
        fields = '__all__'


class UserChangeForm(ModelForm):

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email',)

src/delta_x/api/accounts/views.py
from rest_framework import mixins, status
from rest_framework.response import Response
from rest_framework.decorators import action
from rest_framework.viewsets import GenericViewSet

from delta_x.module.accounts.models import AccountInformation, AccountStatement
from .serializers import (
    AccountSerializer,
    DepositTransactionsSerializer,
    WithdrawTransactionsSerializer,
    TransferTransactionSerializer)
from delta_x.module.cores.permissions import IsBankOwner


class AccountViewSet(mixins.ListModelMixin,
                     mixins.RetrieveModelMixin,
                     GenericViewSet):
    serializer_class = AccountSerializer
    queryset = AccountInformation.objects.filter(is_deleted=False)

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(holder=self.request.user.customer)

    def list(self, request, *args, **kwargs):
        user = request.user
        if not self.request.user.username or getattr(self.request.user, 'customer', None):
            return Response({'Error': 'something worg.'}, status=status.HTTP_401_UNAUTHORIZED)
        queryset = self.filter_queryset(self.get_queryset())
        page = self.paginate_queryset(queryset)
        if page:
            serializer = self.get_serializer(page, many=True)
            return self.get_paginated_response(serializer.data)
        serializer = self.get_serializer(instance=user.customer.accountinformation)
        return Response(serializer.data)

    @action(methods=['get'], detail=False, permission_classes=[IsBankOwner])
    def activate(self, request, **kwargs):
        bank_info = self.get_queryset().first()
        bank_info.is_active = True
        bank_info.save()
        return Response(status=status.HTTP_200_OK)

    @action(methods=['get'], detail=False, permission_classes=[IsBankOwner])
    def deactivate(self, request, **kwargs):
        bank_info = self.get_queryset().first()
        bank_info.is_active = False
        bank_info.save()
        return Response(status=status.HTTP_200_OK)


class DepositViewSet(
        mixins.CreateModelMixin,
        GenericViewSet):

    serializer_class = DepositTransactionsSerializer
    queryset = AccountStatement.objects.filter(is_deleted=False)

    def get_serializer_context(self):
        context = super().get_serializer_context()
        context.update({"request": self.request})
        return context

    def create(self, request, *args, **kwargs):
        data = request.data.copy()
        data['sender'] = request.user.customer.pk
        serializer = self.get_serializer(data=data, context={'request': request})
        if serializer.is_valid():
            response = serializer.save()
            return Response(response, status.HTTP_201_CREATED)
        return Response(serializer.errors, status.HTTP_400_BAD_REQUEST)


class WithdrawViewSet(DepositViewSet):
    serializer_class = WithdrawTransactionsSerializer
    queryset = AccountStatement.objects.filter(is_deleted=False)


class TransferViewSet(DepositViewSet):
    serializer_class = TransferTransactionSerializer
    queryset = AccountStatement.objects.filter(is_deleted=False)

src/delta_x/api/user_and_customer/views.py
from rest_framework.viewsets import ModelViewSet, GenericViewSet
from rest_framework import mixins, status
from rest_framework.response import Response


from delta_x.module.users.models import User, Customer
from .serializers import (UserSerializer, CustomerSerializer)
# Create your views here.


class UserViewSet(ModelViewSet):
    queryset = User.objects.all()
    serializer_class = UserSerializer


class CustomerViewSet(mixins.ListModelMixin,
                      mixins.CreateModelMixin,
                      mixins.RetrieveModelMixin,
                      GenericViewSet):
    queryset = Customer.objects.filter(is_deleted=False).order_by('-created')
    serializer_class = CustomerSerializer

    def list(self, request, *args, **kwargs):
        queryset = self.filter_queryset(self.get_queryset())
        user = request.user
        page = self.paginate_queryset(queryset)
        if page:
            serializer = self.get_serializer(page, many=True)
            return self.get_paginated_response(serializer.data)
        if not user.username:
            return Response({'error': 'you are not auth.'}, status=status.HTTP_401_UNAUTHORIZED)
        if not hasattr(user, 'customer'):
            return Response({'error': 'you are not register customer.'}, status=status.HTTP_404_NOT_FOUND)
        serializer = self.get_serializer(instance=user.customer)
        return Response(serializer.data)

src/delta_x/module/dashboard/authentication/views.py
from django import forms
from django.conf import settings
from django.contrib.auth import get_user_model
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.backends import AllowAllUsersModelBackend
from django.contrib.auth.forms import AuthenticationForm, PasswordResetForm
from django.contrib.auth.tokens import default_token_generator
from django.contrib.auth.views import (LoginView, LogoutView,
                                       PasswordResetCompleteView,
                                       PasswordResetConfirmView,
                                       PasswordResetView)
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.sites.shortcuts import get_current_site
from django.shortcuts import resolve_url
from django.template import loader
from django.urls import reverse_lazy
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode
from django.views.generic.edit import CreateView

from delta_x.module.email.tasks import send_email_reply
from delta_x.module.users.forms import CustomerCreationForm


class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control form-control-lg'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control form-control-lg'}))

    def clean(self):
        username = self.cleaned_data.get('username', None)
        password = self.cleaned_data.get('password', None)

        if username and password:
            backend = AllowAllUsersModelBackend()
            self.user_cache = backend.authenticate(self.request, username=username, password=password)
            if not self.user_cache:
                raise self.get_invalid_login_error()
            else:
                self.confirm_login_allowed(self.user_cache)

        return self.cleaned_data

    def confirm_login_allowed(self, user):
        if not user.is_active:
            raise forms.ValidationError(
                "Please confirm your email so you can log in.",
                code='inactive',
            )


class SignUpViewSet(SuccessMessageMixin, CreateView):
    template_name = 'dashboard/accounts/register.html'
    success_url = reverse_lazy('dashboard:login')
    form_class = CustomerCreationForm
    success_message = "Your profile was created successfully"


class ResetForm(PasswordResetForm):
    def send_mail(self,
                  subject_template_name,
                  email_template_name,
                  context, from_email,
                  to_email,
                  html_email_template_name):
        subject = loader.render_to_string(subject_template_name, context)
        # Email subject *must not* contain newlines
        subject = "".join(subject.splitlines())
        body = loader.render_to_string(email_template_name, context)
        send_email_reply.apply_async(kwargs={
            "subject_template_name": subject,
            "email_template_name": body,
            "context": context,
            "from_email": from_email,
            "to_email": to_email,
            "html_email_template_name": html_email_template_name})

    def save(
        self,
        domain_override=None,
        subject_template_name="registration/password_reset_subject.txt",
        email_template_name="registration/password_reset_email.html",
        use_https=False,
        token_generator=default_token_generator,
        from_email=None,
        request=None,
        html_email_template_name=None,
        extra_email_context=None,
    ):
        """
        Generate a one-use only link for resetting password and send it to the
        user.
        """
        email = self.cleaned_data["email"]
        if not domain_override:
            current_site = get_current_site(request)
            site_name = current_site.name
            domain = current_site.domain
        else:
            site_name = domain = domain_override
        email_field_name = get_user_model().get_email_field_name()
        for user in self.get_users(email):
            user_email = getattr(user, email_field_name)
            context = {
                "email": user_email,
                "domain": domain,
                "site_name": site_name,
                "uid": urlsafe_base64_encode(force_bytes(user.pk)),
                "user": user.email,
                "token": token_generator.make_token(user),
                "protocol": "https" if use_https else "http",
                **(extra_email_context or {}),
            }
            self.send_mail(
                subject_template_name,
                email_template_name,
                context,
                from_email,
                user_email,
                html_email_template_name=html_email_template_name,
            )


class LoginViewSet(LoginView):
    authentication_form = LoginForm
    template_name = 'dashboard/accounts/login.html'
    next_page = reverse_lazy('dashboard:index')

    def form_valid(self, form):
        return super().form_valid(form)

    def form_invalid(self, form):
        context = self.get_context_data(form=form)
        return self.render_to_response(context)


class LogoutViewSet(LogoutView):
    next_page = reverse_lazy('dashboard:login')

    def get_default_redirect_url(self):
        """Return the default redirect URL."""
        auth_logout(self.request)
        if self.next_page:
            return resolve_url(self.next_page)
        elif settings.LOGOUT_REDIRECT_URL:
            return resolve_url(settings.LOGOUT_REDIRECT_URL)
        else:
            return self.request.path


class ResetPasswordViewSet(SuccessMessageMixin, PasswordResetView):
    template_name = "dashboard/accounts/password_reset.html"
    email_template_name = 'dashboard/accounts/password_reset_email.html'
    subject_template_name = 'dashboard/accounts/password_reset_subject.txt'
    form_class = ResetForm
    from_email = settings.EMAIL_HOST_USER
    success_message = "We've emailed you instructions for setting your password, " \
                      "if an account exists with the email you entered. You should receive them shortly." \
                      " If you don't receive an email, " \
                      "please make sure you've entered the address you registered with, and check your spam folder."
    success_url = reverse_lazy("dashboard:password_reset_done")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update(
            {"title": self.title, "subtitle": None, **(self.extra_context or {})}
        )
        return context

    def form_valid(self, form):
        opts = {
            "use_https": self.request.is_secure(),
            "token_generator": self.token_generator,
            "from_email": self.from_email,
            "email_template_name": self.email_template_name,
            "subject_template_name": self.subject_template_name,
            "request": self.request,
            "html_email_template_name": self.html_email_template_name,
            "extra_email_context": self.extra_email_context,
        }
        form.save(**opts)
        return super().form_valid(form)


class PasswordResetConfirmViewSet(PasswordResetConfirmView):
    template_name = "dashboard/accounts/password_reset_confirm.html"


class PasswordResetCompleteViewSet(PasswordResetCompleteView):
    template_name = "dashboard/accounts/password_reset_complete.html"

src/delta_x/module/dashboard/profile/views.py
from django.views.generic import UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy, reverse

from delta_x.module.users.forms import CustomerChangeForm
from delta_x.module.users.models import Customer


class ProfileViews(LoginRequiredMixin, UpdateView):
    template_name = 'dashboard/accounts/profile.html'
    login_url = reverse_lazy('dashboard:login')
    form_class = CustomerChangeForm

    def get_queryset(self):
        queryset = Customer.objects.all()
        return queryset

    def get_success_url(self):
        return reverse('dashboard:profile', kwargs={'pk': self.get_object().id})

    def get_context_data(self, **kwargs):
        customer = Customer.objects.filter(user__id=self.request.user.id).first()
        context = super().get_context_data(**kwargs)
        context['customer_form'] = CustomerChangeForm(initial={
            'address': customer.address,
            'identity_number': customer.identity_number,
            'gender': customer.gender,
        })
        return context

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

src/delta_x/module/dashboard/views.py
import json
import logging

import numpy as np
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import TemplateView
from tensorflow.keras.datasets.mnist import load_data

from delta_x.module.tensorflow_saving.tasks import make_prediction

logger = logging.getLogger(__name__)


class IndexDashboardViews(LoginRequiredMixin, TemplateView):
    template_name = 'dashboard/index.html'
    login_url = reverse_lazy('dashboard:login')

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return self.handle_no_permission()
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        kwargs.setdefault("view", self)
        # load MNIST dataset
        (_, _), (x_test, y_test) = load_data()
        # reshape data to have a single channel
        x_test = x_test.reshape((x_test.shape[0], x_test.shape[1], x_test.shape[2], 1))
        # normalize pixel values
        x_test = x_test.astype('float32') / 255.0
        data = json.dumps({"signature_name": "serving_default", "instances": x_test[0:4].tolist()})
        headers = {"content-type": "application/json"}
        predictions = make_prediction.delay(data=data, headers=headers)
        if self.extra_context is not None:
            kwargs.update(self.extra_context)
        for i, pred in enumerate(predictions.get(timeout=1)['predictions']):
            logger.info(f"True Value: {y_test[i]}, Predicted Value: {np.argmax(pred)}")
        return kwargs

src/delta_x/templates/includes/navigation.html
<!-- [ Header ] start -->
<header class="navbar pcoded-header navbar-expand-lg navbar-light">
    <div class="m-header">
        <a class="mobile-menu" id="mobile-collapse1" href="javascript:"><span></span></a>
        <a href="/" class="b-brand">
            <div class="b-bg">
                <i class="feather icon-trending-up"></i>
            </div>
            <span class="b-title">Delta</span>
        </a>
    </div>
    <a class="mobile-menu" id="mobile-header" href="javascript:">
        <i class="feather icon-more-horizontal"></i>
    </a>
    <div class="collapse navbar-collapse">
        <ul class="navbar-nav mr-auto">
            <li><a href="javascript:" class="full-screen" onclick="javascript:toggleFullScreen()"><i
                    class="feather icon-maximize"></i></a></li>
            <li class="nav-item dropdown">
                <a class="dropdown-toggle" href="javascript:" data-toggle="dropdown">Dropdown</a>
                <ul class="dropdown-menu">
                    <li><a class="dropdown-item" href="javascript:">Action</a></li>
                    <li><a class="dropdown-item" href="javascript:">Another action</a></li>
                    <li><a class="dropdown-item" href="javascript:">Something else here</a></li>
                </ul>
            </li>
            <li class="nav-item">
                <div class="main-search">
                    <div class="input-group">
                        <input type="text" id="m-search" class="form-control" placeholder="Search . . .">
                        <a href="javascript:" class="input-group-append search-close">
                            <i class="feather icon-x input-group-text"></i>
                        </a>
                        <span class="input-group-append search-btn btn btn-primary">
                                <i class="feather icon-search input-group-text"></i>
                            </span>
                    </div>
                </div>
            </li>
        </ul>
        <ul class="navbar-nav ml-auto">
            <li>
                <label>
                    <i class="icon feather icon-sun" id="theme-indicator"></i>
                    <input type="checkbox" id="theme-switch" class="d-none">
                </label>
            </li>
            <li>
                <div class="dropdown">
                    <a class="dropdown-toggle" href="javascript:" data-toggle="dropdown"><i
                            class="icon feather icon-bell"></i></a>
                    <div class="dropdown-menu dropdown-menu-right notification">
                        <div class="noti-head">
                            <h6 class="d-inline-block m-b-0">Notifications</h6>
                            <div class="float-right">
                                <a href="javascript:" class="m-r-10">mark as read</a>
                                <a href="javascript:">clear all</a>
                            </div>
                        </div>
                        <ul class="noti-body">
                            <li class="n-title">
                                <p class="m-b-0">NEW</p>
                            </li>
                            <li class="notification">
                                <div class="media">
                                    <img class="img-radius" src="{{ STATIC_URL  }}images/user/avatar-1.jpg"
                                         alt="Generic placeholder image">
                                    <div class="media-body">
                                        <p><strong>John Doe</strong><span class="n-time text-muted"><i
                                                class="icon feather icon-clock m-r-10"></i>30 min</span></p>
                                        <p>New ticket Added</p>
                                    </div>
                                </div>
                            </li>
                            <li class="n-title">
                                <p class="m-b-0">EARLIER</p>
                            </li>
                            <li class="notification">
                                <div class="media">
                                    <img class="img-radius" src="{{ STATIC_URL  }}images/user/avatar-2.jpg"
                                         alt="Generic placeholder image">
                                    <div class="media-body">
                                        <p><strong>Joseph William</strong><span class="n-time text-muted"><i
                                                class="icon feather icon-clock m-r-10"></i>30 min</span></p>
                                        <p>Prchace New Theme and make payment</p>
                                    </div>
                                </div>
                            </li>
                            <li class="notification">
                                <div class="media">
                                    <img class="img-radius" src="{{ STATIC_URL  }}images/user/avatar-3.jpg"
                                         alt="Generic placeholder image">
                                    <div class="media-body">
                                        <p><strong>Sara Soudein</strong><span class="n-time text-muted"><i
                                                class="icon feather icon-clock m-r-10"></i>30 min</span></p>
                                        <p>currently login</p>
                                    </div>
                                </div>
                            </li>
                        </ul>
                        <div class="noti-footer">
                            <a href="javascript:">show all</a>
                        </div>
                    </div>
                </div>
            </li>
            <li>
                <div class="dropdown drp-user">
                    <a href="javascript:" class="dropdown-toggle" data-toggle="dropdown">
                        <i class="icon feather icon-settings"></i>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right profile-notification">
                        <div class="pro-head">
                            <img src="{{ STATIC_URL  }}images/user/avatar-1.jpg" class="img-radius" alt="User-Profile-Image">
                            <span>
                                {{ request.user.username }}    
                            </span>
                            <a href="/auth-signin.html" class="dud-logout" title="Logout">
                                <i class="feather icon-log-out"></i>
                            </a>
                        </div>
                        <ul class="pro-body">
                            <li><a href="/profile.html" class="dropdown-item"><i class="feather icon-user"></i>
                                Profile</a></li>
                            <li><a href="{% url 'dashboard:logout' %}" class="dropdown-item">
                                <i class="feather icon-lock"></i> Logout</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </li>
        </ul>
    </div>
</header>
<!-- [ Header ] end -->

src/delta_x/templates/includes/scripts.html
<script src="{{ STATIC_URL  }}js/vendor-all.min.js"></script>
<script src="{{ STATIC_URL  }}plugins/bootstrap/js/bootstrap.min.js"></script>
<script src="{{ STATIC_URL  }}js/pcoded.min.js"></script>
<script src="{{ STATIC_URL  }}js/dark-mode.js"></script>